#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

BACKUP_CONFIG=/config
bf-env "BACKUP_CONFIG" "${BACKUP_CONFIG}"

bf-env "DUPLICITY_CONFIG" "${BACKUP_CONFIG}/duplicity"

bf-env "RCLONE_CONFIG" "${BACKUP_CONFIG}/rclone.conf"
bf-env "RCLONE_EXCLUDE_FROM" "${BACKUP_CONFIG}/exclusions.txt"

bf-env "BACKUP_SOURCE" "/b"
bf-env "BACKUP_RESTORE" "/restore"

