#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Set environment variables.
#======================================================================================================================

BACKUP_CONFIG=/config
bf-env "BACKUP_CONFIG" "${BACKUP_CONFIG}"
bf-env "BACKUP_LAST_CRON_LOG" "${BACKUP_CONFIG}/last-cron.log"
bf-env "BACKUP_OPERATIONS_LOG" "${BACKUP_CONFIG}/operations.log"

BACKUP_CONFIG_DUPLICITY="${BACKUP_CONFIG}/duplicity"
bf-env "BACKUP_CONFIG_DUPLICITY" "${BACKUP_CONFIG_DUPLICITY}"
bf-env "BACKUP_DUPLICITY_ARCHIVE" "${BACKUP_CONFIG_DUPLICITY}/archive"
bf-env "BACKUP_DUPLICITY_EXCLUSIONS" "${BACKUP_CONFIG_DUPLICITY}/exclusions.txt"
bf-env "BACKUP_DUPLICITY_LOG" "${BACKUP_CONFIG_DUPLICITY}/log"

BACKUP_CONFIG_RCLONE="${BACKUP_CONFIG}/rclone"
bf-env "BACKUP_CONFIG_RCLONE" "${BACKUP_CONFIG_RCLONE}"

bf-env "BACKUP_SOURCE" "/b"

bf-env "BACKUP_RESTORE" "/restore"


#======================================================================================================================
# Set duplicity environment variables.
#======================================================================================================================

bf-env "PASSPHRASE" "${BACKUP_PASSPHRASE-}"


#======================================================================================================================
# Set rclone environment variables.
#======================================================================================================================

bf-env "RCLONE_CONFIG" "${BACKUP_CONFIG_RCLONE}/rclone.conf"
bf-env "RCLONE_CONFIG_PASS" "${BACKUP_PASSPHRASE-}"
bf-env "RCLONE_EXCLUSIONS" "${BACKUP_CONFIG_RCLONE}/exclusions.txt"
bf-env "RCLONE_LOG_FILE" "${BACKUP_CONFIG_RCLONE}/log"
