#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# If the 'running' file exists, delete it.
#======================================================================================================================

if [ -f "${BACKUP_RUNNING}" ] ; then
    bf-debug "Deleting ${BACKUP_RUNNING}."
    rm -f ${BACKUP_RUNNING}
fi
