#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Ensure rclone exclusions file exists.
#======================================================================================================================

[[ ! -f ${RCLONE_EXCLUDE_FROM} ]] \
    && touch ${RCLONE_EXCLUDE_FROM}
