#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Clear everything in /restore.
#======================================================================================================================

bf-echo "Removing everything in ${BACKUP_RESTORE}..." "clear-restore"
bf-rmrf "${BACKUP_RESTORE}/*"
bf-done "clear-restore"
