#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Verify rclone configuration.
#======================================================================================================================

rclone config show ${BACKUP_RCLONE_STORAGE} > /dev/null 2>&1
