#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Create file if it does not exist.
# Arguments:
#   1   Absolute path to file to check / create.
#======================================================================================================================

create-if-not-exists () {
    [[ -f "${1}" ]] || touch "${1}"
}


#======================================================================================================================
# Verify operations log files.
#======================================================================================================================

bf-debug "Verifying setup..." "test-setup"
bf-debug " .. operations logs" "test-setup"

create-if-not-exists ${BACKUP_LAST_CRON_LOG}
create-if-not-exists ${BACKUP_OPERATIONS_LOG}


#======================================================================================================================
# Verify passphrase.
#======================================================================================================================

bf-debug " .. passphrase" "test-setup"

[[ -z "${BACKUP_PASSPHRASE-}" ]] \
    && bf-error "You must define BACKUP_PASSPHRASE." "test-setup"


#======================================================================================================================
# Verify duplicity setup.
#======================================================================================================================

bf-debug " .. duplicity" "test-setup"

mkdir -p ${BACKUP_DUPLICITY_ARCHIVE}
create-if-not-exists ${BACKUP_DUPLICITY_EXCLUSIONS}
create-if-not-exists ${BACKUP_DUPLICITY_LOG}


#======================================================================================================================
# Verify rclone setup.
#======================================================================================================================

bf-debug " .. rclone" "test-setup"

[[ -f ${RCLONE_CONFIG} ]] \
    || bf-error "rclone configuration not found." "test-setup"

[[ ${BF_LIB}/test-rclone-storage ]] \
    || bf-error "rclone storage '${BACKUP_RCLONE_STORAGE}' is not defined." "test-setup"

mkdir -p ${BACKUP_CONFIG_RCLONE}
create-if-not-exists ${BACKUP_RCLONE_EXCLUSIONS}
create-if-not-exists ${BACKUP_RCLONE_LOG}


#======================================================================================================================
# Done.
#======================================================================================================================

bf-debug "Test complete." "test-setup"
