#!/command/with-contenv sh

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Check for passphrase.
#======================================================================================================================

bf-debug "Verifying setup."

[[ -z "${BACKUP_DUPLICITY_PASSPHRASE-}" ]] \
    && bf-error "You must define BACKUP_DUPLICITY_PASSPHRASE." "test-setup"


#======================================================================================================================
# Verify rclone configuration.
#======================================================================================================================

[[ -f ${RCLONE_CONFIG} ]] \
    || bf-error "rclone configuration not found." "test-setup"

[[ ${BF_LIB}/test-rclone-storage ]] \
    || bf-error "rclone storage '${BACKUP_RCLONE_STORAGE}' is not defined." "test-setup"

[[ ! -f ${RCLONE_EXCLUDE_FROM} ]] \
    && touch ${RCLONE_EXCLUDE_FROM}


#======================================================================================================================
# Done.
#======================================================================================================================

bf-debug "Test complete."
