#!/command/with-contenv sh

set -euo pipefail


#======================================================================================================================
# Verify operations log files.
#======================================================================================================================

bf-debug "Verifying setup..." "test-setup"
bf-debug " .. operations logs" "test-setup"

touch ${BACKUP_LAST_CRON_LOG}
touch ${BACKUP_OPERATIONS_LOG}


#======================================================================================================================
# Verify passphrase.
#======================================================================================================================

bf-debug " .. passphrase" "test-setup"

[[ -z "${BACKUP_PASSPHRASE-}" ]] \
    && bf-error "You must define BACKUP_PASSPHRASE." "test-setup"


#======================================================================================================================
# Verify duplicity setup.
#======================================================================================================================

bf-debug " .. duplicity" "test-setup"

mkdir -p ${DUPLICITY_ARCHIVE}
touch ${DUPLICITY_EXCLUSIONS}
touch ${DUPLICITY_LOG}


#======================================================================================================================
# Verify rclone setup.
#======================================================================================================================

bf-debug " .. rclone" "test-setup"

[[ -f ${RCLONE_CONFIG} ]] \
    || bf-error "rclone configuration not found." "test-setup"

[[ ${BF_LIB}/test-rclone-storage ]] \
    || bf-error "rclone storage '${BACKUP_RCLONE_STORAGE}' is not defined." "test-setup"

mkdir -p ${BACKUP_CONFIG_RCLONE}
touch ${RCLONE_EXCLUSIONS}
touch ${RCLONE_LOG}


#======================================================================================================================
# Done.
#======================================================================================================================

bf-debug "Test complete." "test-setup"
